import i18next from "i18next";
import fa from "./navigation-i18n/fa";
import ar from "./navigation-i18n/ar";
import en from "./navigation-i18n/en";
import tr from "./navigation-i18n/tr";
import SettingsAppNavigation from "../main/apps/settings/SettingsAppNavigation";

i18next.addResourceBundle("fa", "navigation", fa);
i18next.addResourceBundle("en", "navigation", en);
i18next.addResourceBundle("tr", "navigation", tr);
i18next.addResourceBundle("ar", "navigation", ar);
/**
 * The navigationConfig object is an array of navigation items for the Fuse application.
 */

const navigationConfig = [
  {
    id: "dashboards",
    title: "Dashboards",
    subtitle: "Dashboard section of your app",
    type: "group",
    icon: "heroicons-outline:home",
    translate: "DASHBOARDS",
    subtitleTranslate: "SUB_DASHBOARDS",
    children: [
      {
        id: "dashboards.project",
        title: "سیستم",
        type: "item",
        icon: "heroicons-outline:clipboard-check",
        url: "/",
        translate: undefined,
      },
      {
        id: "dashboards.finance",
        title: "Finance",
        type: "item",
        icon: "heroicons-outline:cash",
        url: "/dashboards/finance",
        translate: "FINANCE",
      },
    ],
  },
  {
    id: 'archive',
    title: 'آرشیو',
    subtitle: 'مدیریت آرشیوها',
    type: 'group',
    icon: 'heroicons-outline:archive',
    translate: 'مدیریت آرشیو',
    children: [
      {
        id: 'archives',
        title: 'آرشیوها',
        type: 'item',
        icon: 'heroicons-outline:archive-box',
        url: '/apps/archive',
      },
      {
        id: 'archiveTasks',
        title: 'وظایف آرشیو',
        type: 'item',
        icon: 'heroicons-outline:clipboard-list',
        url: '/apps/archive-tasks',
      },
    ],
  },
  {
    id: 'subscriptions',
    title: 'اشتراک‌ها',
    subtitle: 'مدیریت اشتراک‌ها',
    type: 'group',
    icon: 'heroicons-outline:credit-card',
    translate: 'مدیریت اشتراک',
    children: [
      {
        id: 'subscriptions.list',
        title: 'مدیریت اشتراک‌ها',
        type: 'item',
        icon: 'heroicons-outline:credit-card',
        url: '/apps/subscriptions',
        subtitle: 'لیست تمامی اشتراک های فعال و غیر فعال',
      },
    ],
  },
  {
    id: "category",
    title: "category",
    subtitle: "Category section of your app",
    type: "group",
    icon: "heroicons-outline:home",
    translate: "CATEGORY",
    subtitleTranslate: "SUB_CATEGORY",
    children: [
      {
        id: "category.list",
        title: "List of Categories",
        type: "item",
        icon: "heroicons-outline:clipboard-check",
        url: "/category/list",
        end: true,
        translate: "CATEGORY_LIST",
      },
      {
        id: "category.subcategory.list",
        title: "Get all subcategories list",
        type: "item",
        icon: "heroicons-outline:clipboard-check",
        url: "/category/subcategory/list",
        end: true,
        translate: "SUB_SUB_CATEGORY_LIST",
      },
    ],
  },
  {
    id: "banks",
    title: "Banks",
    translate: "BANKS",
    subtitle: "All of the banks",
    type: "group",
    icon: "heroicons-outline:cube",
    children: [
      {
        id: "banks.food-industry-bank",
        title: "FoodIndustryBank",
        translate: "FOOD_INDUSTRY_BANK",
        type: "collapse",
        icon: "heroicons-outline:shopping-cart",
        children: [
          {
            id: "banks.food-industry-bank.list",
            title: "FoodIndustryBankList",
            translate: "COMPANY_LIST",
            type: "item",
            url: "banks/food-industry",
            end: true,
          },
          {
            id: "banks.food-industry-bank.requests",
            title: "USER_REQUESTS",
            translate: "USER_REQUESTS",
            type: "item",
            url: "banks/food-industry/request/list",
          },
          {
            id: "banks.food-industry-bank.archive",
            title: "BANK_ARCHIVE",
            translate: "BANK_ARCHIVE",
            type: "item",
            url: "banks/food-industry/archive",
          },
        ],
      },
      {
        id: "banks.agriculture-industry-bank",
        title: "AgricultureIndustryBank",
        translate: "AGRICULTURE_INDUSTRY_BANK",
        type: "collapse",
        icon: "heroicons-outline:shopping-cart",
        children: [
          {
            id: "banks.agriculture-industry-bank.list",
            title: "AgricultureIndustryBankList",
            translate: "COMPANY_LIST",
            type: "item",
            url: "banks/agriculture-industry",
            end: true,
          },
          {
            id: "banks.agriculture-industry-bank.requests",
            title: "USER_REQUESTS",
            translate: "USER_REQUESTS",
            type: "item",
            url: "banks/agriculture-industry/request/list",
          },
          {
            id: "banks.agriculture-industry-bank.archive",
            title: "BANK_ARCHIVE",
            translate: "BANK_ARCHIVE",
            type: "item",
            url: "banks/agriculture-industry/archive",
          },
        ],
      },
          {
            id: "banks.service-bank.list",
            title: "ServiceBankList",
            translate: "SERVICE_BANK",
            type: "item",
            url: "banks/service",
            icon: "heroicons-outline:shopping-cart",
            end: true,
      },
    ],
  },
  {
    id: "weblog",
    title: "وبلاگ",
    subtitle: "مدیریت وبلاگ",
    type: "group",
    icon: "heroicons-outline:newspaper",
    translate: "WEBLOG",
    subtitleTranslate: "SUB_WEBLOG",
    children: [
      {
        id: "weblog.dashboard",
        title: "داشبورد وبلاگ",
        type: "item",
        icon: "heroicons-outline:chart-bar",
        url: "/apps/weblog/dashboard",
      },
      {
        id: "weblog.posts",
        title: "نوشته‌ها",
        type: "item",
        icon: "heroicons-outline:document-text",
        url: "/apps/weblog/posts",
      },
      {
        id: "weblog.categories",
        title: "دسته‌بندی‌ها",
        type: "item",
        icon: "heroicons-outline:folder",
        url: "/apps/weblog/categories",
      },
      {
        id: "weblog.tags",
        title: "برچسب‌ها",
        type: "item",
        icon: "heroicons-outline:tag",
        url: "/apps/weblog/tags",
      },
      {
        id: "weblog.media",
        title: "رسانه‌ها",
        type: "item",
        icon: "heroicons-outline:photograph",
        url: "/apps/weblog/media",
      },
    ],
  },
  {
    id: "apps",
    title: "Applications",
    subtitle: "Panel applications section",
    type: "group",
    icon: "heroicons-outline:cube",
    translate: "APPLICATIONS",
    subtitleTranslate: "SUB_APPLICATIONS",
    children: [
      {
        id: "apps.excel-template-manager",
        title: "Excel Template Manager",
        type: "item",
        icon: "heroicons-outline:paper-airplane",
        url: "/apps/excel-templates",
        translate: "EXCEL_TEMPLATE_MANAGER",
      },
      {
        id: "apps.message-manager",
        title: "Message Manager",
        type: "item",
        icon: "heroicons-outline:mail",
        url: "/apps/message-manager/templates",
        translate: "MESSAGE_MANAGER",
      },
      {
        id: "apps.message-manager-history",
        title: "Messaging History",
        type: "item",
        icon: "heroicons-outline:clock",
        url: "/apps/message-manager/history",
        translate: "MESSAGING_HISTORY",
      },
      {
        id: "apps.notification-admin",
        title: "Notification Admin",
        type: "collapse",
        icon: "heroicons-outline:bell",
        translate: "NOTIFICATION_ADMIN",
        children: [
          {
            id: "apps.notification-admin.channels",
            title: "Notification Channels",
            type: "item",
            icon: "heroicons-outline:rss",
            url: "/apps/notification-admin/channels",
            translate: "NOTIFICATION_CHANNELS",
          },
          {
            id: "apps.notification-admin.configs",
            title: "Notification Configs",
            type: "item",
            icon: "heroicons-outline:cog",
            url: "/apps/notification-admin/configs",
            translate: "NOTIFICATION_CONFIGS",
          },
          {
            id: "apps.notification-admin.constraints",
            title: "Notification Constraints",
            type: "item",
            icon: "heroicons-outline:shield-check",
            url: "/apps/notification-admin/constraints",
            translate: "NOTIFICATION_CONSTRAINTS",
          },
          {
            id: "apps.notification-admin.events",
            title: "Internal Events",
            type: "item",
            icon: "heroicons-outline:lightning-bolt",
            url: "/apps/notification-admin/events",
            translate: "INTERNAL_EVENTS",
          },
        ],
      },
      {
        id: "apps.credit-manager",
        title: "Credit Manager",
        type: "item",
        icon: "heroicons-outline:paper-airplane",
        url: "/apps/credit-manager",
        translate: "CREDIT_MANAGER",
      },
      {
        id: "apps.announcement-builder",
        title: "Announcement Builder",
        type: "item",
        icon: "heroicons-outline:paper-airplane",
        url: "/apps/announcement-builder",
        translate: "ANNOUNCEMENT_BUILDER",
      },
      {
        id: "apps.page-builder",
        title: "PageBuilder",
        type: "item",
        icon: "heroicons-outline:paper-airplane",
        url: "/apps/page-builder",
        translate: "PAGE_BUILDER",
      },
      {
        id: "apps.excel",
        title: "Excel",
        type: "item",
        icon: "heroicons-outline:document",
        url: "/apps/excel",
        translate: "EXCEL",
      },
      {
        id: "apps.epub",
        title: "EPub",
        type: "item",
        icon: "heroicons-outline:document",
        url: "/apps/epub",
        translate: "EPUB",
      },
      {
        id: "apps.ticketing",
        title: "Ticketing",
        type: "item",
        icon: "heroicons-outline:chat-alt",
        url: "/apps/ticketing",
        translate: "TICKETING",
      },
      {
        id: "apps.notifications",
        title: "Notifications",
        type: "item",
        icon: "heroicons-outline:bell",
        url: "/apps/notifications",
        translate: "NOTIFICATIONS",
      },
      {
        id: "apps.requests",
        title: "Requests",
        type: "item",
        icon: "heroicons-outline:bell",
        url: "/apps/requests",
        translate: "REQUESTS",
      },
      {
        ...SettingsAppNavigation,
        type: "item",
        badge: {
          title: "NEW",
        },
      },
    ],
  },
  {
    id: "bulk_messaging",
    title: "BulkMessaging",
    translate: "BULK_MESSAGING",
    subtitle: "Bulk messaging section",
    subtitleTranslate: "SUB_BULK_MESSAGING",
    type: "group",
    icon: "heroicons-outline:speakerphone",
    children: [
      {
        id: "bulk_messaging.compose",
        title: "BulkMessagingCompose",
        translate: "BULK_MESSAGING_COMPOSE",
        type: "item",
        icon: "heroicons-outline:pencil-alt",
        url: "/apps/bulk-messaging/compose",
      },
      {
        id: "bulk_messaging.tasks",
        title: "BulkMessagingTasks",
        translate: "BULK_MESSAGING_TASKS",
        type: "item",
        icon: "heroicons-outline:clipboard-list",
        url: "/apps/bulk-messaging/tasks",
      },
    ],
  },
  {
    id: "users",
    title: "Users",
    translate: "USERS_LIST",
    subtitle: "Users List Section",
    subtitleTranslate: "SUB_USERS",
    type: "group",
    icon: "heroicons-outline:cube",
    children: [
      {
        id: "users.list",
        title: "UserList",
        translate: "USERS_LIST",
        type: "item",
        icon: "heroicons-outline:user-group",
        url: "/apps/users",
      },
      {
        id: "users.roles",
        title: "مدیریت نقش‌ها",
        translate: "ROLES_MANAGEMENT",
        type: "item",
        icon: "heroicons-outline:shield-check",
        url: "/apps/roles",
      },
      {
        id: "users.news-letter",
        title: "UsersNewsLetter",
        translate: "USERS_NEWS_LETTER",
        type: "item",
        subtitleTranslate: "USERS_NEWS_LETTER",
        icon: "heroicons-outline:academic-cap",
        url: "/newsletters",
      },
    ],
  },
];
export default navigationConfig;
